### ISSUE TITLE
Integrate CERN use case

### ISSUE THREAD

**Issue by matbun** [interTwin-eu/itwinai#41]
**Tasks**:

- [ ] Adapt CERN use case to PyTorch Lightning starting from this [tutorial](https://lightning.ai/docs/pytorch/stable/notebooks/lightning_examples/basic-gan.html)
- [ ] Integrate use case into itwinai followin [this guide](https://intertwin-eu.github.io/T6.5-AI-and-ML/docs/How-to-use-this-software.html)
- [ ] Write tests under `tests/use-cases/` for the newly integrated use case
